rails/myblog/config/routes.rb
Rails.application.routes.draw do
  get "home/index", to: "home#index"
  resources :tags
  devise_for :users
  resources :categories
  root "home#index"
  resources :posts #RESTful routing - generated by scafffold magic
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "categories/search/:cat", to: "categories#search", :as => :cat_post
  get "home/tags/:tag", to: "home#search", :as => :tag_search
end

rails/myblog/app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :title, presence: true
end

rails/myblog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :taggings
  has_many :tags, through: :taggings

  validates :title, presence: true
  has_rich_text :body

  def all_tags=(tags)
    if tags.blank?
      return
    end

    self.tags = tags.split(",").map do |name|
      unless name.blank?
        Tag.where(name: name.strip).first_or_create!
      end
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

rails/myblog/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings
  validates :name, presence: true
end

rails/myblog/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

rails/myblog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :username, uniqueness: true
end

rails/myblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_user_params, if: :devise_controller?

  protected

  def configure_user_params
    devise_parameter_sanitizer
      .permit(:sign_up, keys: [:username, :admin, :email, :password])

    devise_parameter_sanitizer
      .permit(:account_update, keys: [:username, :admin, :email, :password, :current_password])
  end
end

rails/myblog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  def search
    
    if params.has_key?(:cat)
        @posts = Category.find_by(:title =>params[:cat]).posts
    end #if
  end #search

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:title)
  end

  
end 

rails/myblog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order("created_at desc")
    respond_to do |format|
      format.html #index.htnml.erb
      format.json { render json: @posts }
    end
  end #eod of index

  def search
   if params.has_key?(:tag)
      @posts = Tag.find_by(:name =>params[:tag]).posts
   end #if
  end #search
end

rails/myblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at desc").page(params[:page]).per(10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # byebug #debugger added for testing........
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id, :all_tags)
  end
end

rails/myblog/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name, :string)
  end
end

rails/myblog/app/helpers/home_helper.rb
module HomeHelper
end

rails/myblog/app/helpers/tags_helper.rb
module TagsHelper
end

rails/myblog/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [800, 600] : [1024, 768]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

rails/myblog/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render "form", category: @category %>

<%= link_to "Show", @category %> |
<%= link_to "Back", categories_path %>

rails/myblog/app/views/categories/index.html.erb
<h1>Categories</h1>

<%= link_to "New Category", new_category_path, class: "btn btn-primary" %>
<table class=" table table-striped table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Posts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to category.posts.count,cat_post_path(category.title) %></td>
        <td><%= link_to "Show", category %></td>
        <td><%= link_to "Edit", edit_category_path(category) %></td>
        <td><%= link_to "Destroy", category, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails/myblog/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form", category: @category %>

<%= link_to "Back", categories_path %>

rails/myblog/app/views/categories/search.html.erb
<div class="row">
<% @posts.each do |post| %>
    <div class ="col-md-12 mb-4">
        <div class="card">
            <div class="card-header">
                <%= post.title %>
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p><%= post.body %> </p>
                    <footer class="blockquote-footer">
                        posted on
                        <cite title="Source Title">
                            <%= time_ago_in_words post.created_at %>
                        </cite>
                    </footer>
                </blockquote>
            </div>
        </div>
    </div>
<% end %>
</div>

rails/myblog/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to "Edit", edit_category_path(@category) %> |
<%= link_to "Back", categories_path %>

rails/myblog/app/views/home/index.html.erb
<div class="row">
<% @posts.each do |post| %>
    <div class ="col-md-12 mb-4">
        <div class="card">
            <div class="card-header">
                <%= post.title %>
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p><%= post.body %> </p>
                    <footer class="blockquote-footer">
                        posted on
                        <cite title="Source Title">
                            <%= time_ago_in_words post.created_at %>
                        </cite>
                    </footer>
                </blockquote>
            </div>
        </div>
    </div>
<% end %>
</div>

rails/myblog/app/views/home/search.html.erb
<div class="row">
<% @posts.each do |post| %>
    <div class ="col-md-12 mb-4">
        <div class="card">
            <div class="card-header">
                <%= post.title %>
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p><%= post.body %> </p>
                    <footer class="blockquote-footer">
                        posted on
                        <cite title="Source Title">
                            <%= time_ago_in_words post.created_at %>
                        </cite>
                    </footer>
                </blockquote>
            </div>
        </div>
    </div>
<% end %>
</div>

rails/myblog/app/views/layouts/_meta_nav.html.erb
 <div class="col-md-2">
                <ul class="list-group">
                  <li class="list-group-item"> <%= link_to "Posts", posts_path %> </li>
                  <li class="list-group-item"> <%= link_to "Category", categories_path %> </li>
                  <li class="list-group-item"> <%= link_to "Manage Tag", tags_path %> </li>
                 
                </ul>
</div>

rails/myblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" crossorigin="anonymous">
  </head>

  <body>
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>
  <div class="container">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
      <%= link_to "Dhruv DWIVEDI", root_path %>
      </h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">About Me</a>
        <a class="p-2 text-dark" href="#">Contact</a>
        <a class="p-2 text-dark" href="#">Projects</a>
        <a class="p-2 text-dark" href="#">Resume</a>
      </nav>
      <% if user_signed_in? %>
        <span class="badge badge-primary text-dark">Welcome <%= current_user.username %></span>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "p-2 btn btn-outline-primary" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "p-2 btn btn-outline-primary" %>
      <% end %>
      <!--<a class="btn btn-outline-primary" href="#">Sign up</a> -->
    </div>

  </div>
    <div class="container">
      <div class="row">
        <% if user_signed_in? %>
          <%= render "layouts/meta_nav" %>
        <% end %>

        <div class="col-md-9">
            <%= yield %>
        </div>

        <% if controller.controller_name == "home" %>
          <div class="col-md-3">
            <h2>TAGS:</h2>
              <% Tag.all.each do |t| %>
                <span class="badge badge-info"><%= link_to t.name, tag_search_path(t.name) %></span>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>
    
     
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>

  </body>
</html>

rails/myblog/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

   <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :title %>
  </div>

  <div class="field">
  <%= form.label :new_tag_id %>
    <%= form.text_field :all_tags, placeholder: "Tags seperated with comma" %>
  </div>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.collection_select :tag_ids, Tag.all, :id, :name, { include_blank: true }, { :multiple => true } %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails/myblog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render "form", post: @post %>

<%= link_to "Show", @post %> |
<%= link_to "Back", posts_path %>

rails/myblog/app/views/posts/index.html.erb
<h1>Posts</h1>
<%= paginate @posts, remote: false %>
<%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
<table class=" table table-striped table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Category</th>
      <th>Tags</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.category.title %></td>
        <td><%= post.tags.pluck(:name).join(",") %></td>
        <td><%= link_to "Show", post %></td>
        <td><%= link_to "Edit", edit_post_path(post) %></td>
        <td><%= link_to "Destroy", post, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

rails/myblog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

<%= link_to "Back", posts_path %>

rails/myblog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category.title %>
</p>

<div class="rows">
  <div class="col-sm-12">
      <% @post.tags.each do |tag| %>
        <span class="badge badge-warning"><%= tag.name %></span>
      <% end %>    
  </div>
</div>

<%= link_to "Edit", edit_post_path(@post) %> |
<%= link_to "Back", posts_path %>